version: "3.4"

x-common-variables: &common-variables
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: sr05facebook
  MYSQL_PORT: "${APP_SQL}"
  NODE_PORT: "${APP_NODE}"
  REACT_APP_SERVER_PORT: "${APP_FRONT}"
  REACT_APP_API: "${APP_NODE}"

services:
  mysql-db:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${APP_SQL}:3306
    restart: unless-stopped
    volumes:
      - ./db/${APP_NODE}.sql:/docker-entrypoint-initdb.d/${APP_NODE}.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - ${APP_PHP}:80
    restart: always
  server:
    build: ./back-end
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - ${APP_NODE}:8000
    volumes:
      - ./back-end:/app
    links:
      - mysql-db
    networks:
      - backend
      - default
    command: npm start
  client:
    build:
      context: ./front-end
      args:
        BACK_PORT: ${APP_NODE}
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - ${APP_FRONT}:3000
    volumes:
      - ./front-end/src:/app/src
    links:
      - server
    command: npm start

networks:
  backend:
      name: node-network

